server:
  port: 8081

#DB Configuration
spring:
  datasource:
    name: upload
    url: jdbc:mysql://localhost:3306/crawler?useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=UTC
    username: root
    password: 123
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

mybatis:
  #实体类所做包
  type-aliases-package: com.tang.jddemo.model
  #mapper.xml所在位置
  mapper-locations: classpath:mapper/*.xml