package com.tang.jddemo.model;

import java.util.Date;

public class JDItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd_item.id
     *
     * @mbggenerated Tue May 21 17:48:49 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd_item.spu
     *
     * @mbggenerated Tue May 21 17:48:49 CST 2019
     */
    private Long spu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd_item.sku
     *
     * @mbggenerated Tue May 21 17:48:49 CST 2019
     */
    private Long sku;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd_item.title
     *
     * @mbggenerated Tue May 21 17:48:49 CST 2019
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd_item.price
     *
     * @mbggenerated Tue May 21 17:48:49 CST 2019
     */
    private Long price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd_item.pic
     *
     * @mbggenerated Tue May 21 17:48:49 CST 2019
     */
    private String pic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd_item.url
     *
     * @mbggenerated Tue May 21 17:48:49 CST 2019
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd_item.created
     *
     * @mbggenerated Tue May 21 17:48:49 CST 2019
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd_item.updated
     *
     * @mbggenerated Tue May 21 17:48:49 CST 2019
     */
    private Date updated;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd_item.id
     *
     * @return the value of jd_item.id
     *
     * @mbggenerated Tue May 21 17:48:49 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd_item.id
     *
     * @param id the value for jd_item.id
     *
     * @mbggenerated Tue May 21 17:48:49 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd_item.spu
     *
     * @return the value of jd_item.spu
     *
     * @mbggenerated Tue May 21 17:48:49 CST 2019
     */
    public Long getSpu() {
        return spu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd_item.spu
     *
     * @param spu the value for jd_item.spu
     *
     * @mbggenerated Tue May 21 17:48:49 CST 2019
     */
    public void setSpu(Long spu) {
        this.spu = spu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd_item.sku
     *
     * @return the value of jd_item.sku
     *
     * @mbggenerated Tue May 21 17:48:49 CST 2019
     */
    public Long getSku() {
        return sku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd_item.sku
     *
     * @param sku the value for jd_item.sku
     *
     * @mbggenerated Tue May 21 17:48:49 CST 2019
     */
    public void setSku(Long sku) {
        this.sku = sku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd_item.title
     *
     * @return the value of jd_item.title
     *
     * @mbggenerated Tue May 21 17:48:49 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd_item.title
     *
     * @param title the value for jd_item.title
     *
     * @mbggenerated Tue May 21 17:48:49 CST 2019
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd_item.price
     *
     * @return the value of jd_item.price
     *
     * @mbggenerated Tue May 21 17:48:49 CST 2019
     */
    public Long getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd_item.price
     *
     * @param price the value for jd_item.price
     *
     * @mbggenerated Tue May 21 17:48:49 CST 2019
     */
    public void setPrice(Long price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd_item.pic
     *
     * @return the value of jd_item.pic
     *
     * @mbggenerated Tue May 21 17:48:49 CST 2019
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd_item.pic
     *
     * @param pic the value for jd_item.pic
     *
     * @mbggenerated Tue May 21 17:48:49 CST 2019
     */
    public void setPic(String pic) {
        this.pic = pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd_item.url
     *
     * @return the value of jd_item.url
     *
     * @mbggenerated Tue May 21 17:48:49 CST 2019
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd_item.url
     *
     * @param url the value for jd_item.url
     *
     * @mbggenerated Tue May 21 17:48:49 CST 2019
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd_item.created
     *
     * @return the value of jd_item.created
     *
     * @mbggenerated Tue May 21 17:48:49 CST 2019
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd_item.created
     *
     * @param created the value for jd_item.created
     *
     * @mbggenerated Tue May 21 17:48:49 CST 2019
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd_item.updated
     *
     * @return the value of jd_item.updated
     *
     * @mbggenerated Tue May 21 17:48:49 CST 2019
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd_item.updated
     *
     * @param updated the value for jd_item.updated
     *
     * @mbggenerated Tue May 21 17:48:49 CST 2019
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
}